FROM python:3.10-slim-buster

RUN apt-get update && apt-get install -y git

COPY cpu-requirements.txt /tmp/
RUN pip install --upgrade pip
RUN pip install uv
RUN uv venv && \
    . .venv/bin/activate && \
    uv pip install -r /tmp/cpu-requirements.txt

WORKDIR /usr/src

RUN git clone https://github.com/PulmonaryMRI/imoco_recon.git

RUN mkdir -p /usr/data/sample_data
